apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobula.name" . }}-registry
  labels: {{- include "mobula.labels" . | nindent 4 }}
data:
  clusters.toml: |
    {{- range .Values.clusters }}
    [[clusters]]
    id = {{ .id | quote }}
    hostname = {{ .hostname | quote }}
    api_base_url = {{ .api_base_url | quote }}
    {{- if .auth_token }}
    auth_token = {{ .auth_token | quote }}
    {{- end }}
    {{- end }}
